/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package DesafioBootcamp;

import java.time.LocalDate;

public class App {
    

    public static void main(String[] args) {
        Curso curso = new Curso();
        curso.setTitulo("Java");
        curso.setDescricao("descrição do curso");
        curso.setCargaHoraria(8);
        
        Curso curso2 = new Curso();
        curso2.setTitulo("Javascript");
        curso2.setDescricao("descrição do curso");
        curso2.setCargaHoraria(6);
        
        System.out.println(curso);
        
        Mentoria mentoria1 = new Mentoria();
        mentoria1.setTitulo("mentoria de Java");
        mentoria1.setDescricao("descrição da mentoria");
        mentoria1.setData(LocalDate.now());
        
        Bootcamp bootcamp = new Bootcamp();
        bootcamp.setNome("Bootcamp Java Developer");
        bootcamp.setDescricao("Descrição Bootcamp Java Developer");
        bootcamp.getConteudos().add(curso);
        bootcamp.getConteudos().add(curso2);
        bootcamp.getConteudos().add(mentoria1);
        
        Dev devCamila = new Dev();
        devCamila.setNome("Camila");
        devCamila.inscreverBootcamp(bootcamp);
        System.out.println("Conteudos inscritos" + devCamila.getConteudosInscritos());
        devCamila.progredir();
        System.out.println("XP: " + devCamila.calcularXp());
        devCamila.progredir();
        System.out.println("XP: " + devCamila.calcularXp());
        System.out.println("Conteudos inscritos" + devCamila.getConteudosInscritos());
        System.out.println("Conteudos concluídos" + devCamila.getConteudosConcluidos());
        
        /*Dev devAndreia = new Dev();
        devAndreia.setNome("Andreia");
        devAndreia.inscreverBootcamp(bootcamp);
        System.out.println("Conteudos inscritos" + devCamila.getConteudosInscritos());
        devAndreia.progredir();
        System.out.println("Conteudos inscritos" + devAndreia.getConteudosInscritos());
        System.out.println("Conteudos concluídos" + devAndreia.getConteudosConcluidos());*/

    }
}
